export enum AgeGroup {
  ONE_TO_THREE = "ONE_TO_THREE",
  FOUR_TO_SIX = "FOUR_TO_SIX",
  SEVEN_TO_TEN = "SEVEN_TO_TEN",
  ELEVEN_TO_FOURTEEN = "ELEVEN_TO_FOURTEEN",
  FIFTEEN_TO_EIGHTTEEN = "FIFTEEN_TO_EIGHTTEEN",
  NINETEEN_TO_SIXTYNINE = "NINETEEN_TO_SIXTYNINE",
  OVER_SIXTYNINE = "OVER_SIXTYNINE"
}
