export enum AgeGroup {
  ONE_TO_THREE = "1-3",
  FOUR_TO_SIX = "4-6",
  SEVEN_TO_TEN = "7-10",
  ELEVEN_TO_FOURTEEN = "11-14",
  FIFTEEN_TO_EIGHTTEEN = "15-18",
  NINETEEN_TO_SIXTYNINE = "19-29",
  OVER_SIXTYNINE = "29 fölött"
}
