export enum Allergen {
    MILK="MILK",
    GLUTEN="GLUTEN",
    EGG="EGG",
    SHELLFISH="SHELLFISH",
    FISH="FISH",
    MOLLUSCS="MOLLUSC",
    PEANUT="PEANUT",
    WALNUT="WALNUT",
    SESAME="SESAME",
    SOY="SOY",
    CELERY="CELERY",
    MUSTARD="MUSTARD",
    SULPITHES="SULPITHES",
    LUPIN="LUPIN"
}
